name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0-127.0.dev

# Add regular dependencies here.
dependencies:
  checked_exceptions:
    path: ../
  # path: ^1.8.0

dev_dependencies:
  custom_lint: ^0.5.7
  lints: ^3.0.0
  test: ^1.24.0
