name: checked_exceptions
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0-127.0.dev

# Add regular dependencies here.
dependencies:
  analyzer: ^6.3.0
  analyzer_plugin: ^0.11.3
  collection: ^1.18.0
  custom_lint_builder: ^0.5.7
  meta: ^1.9.0
  # path: ^1.8.0

dev_dependencies:
  lint: ^2.2.0
  lints: ^3.0.0
  test: ^1.24.0
